<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Shared</RootNamespace>
    <AssemblyName>Shared</AssemblyName>
    <LangVersion>9</LangVersion>
    <Deterministic>true</Deterministic>
    <EnableDefaultItems>false</EnableDefaultItems>
    <OutputPath>..\..\1.6\Assemblies</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Files\*.cs" />
    <Compile Include="Misc\*.cs" />
    <Compile Include="Network\ListenerBase.cs" />
    <Compile Include="Network\Packets\Data\*.cs" />
    <Compile Include="Network\Packets\Details\*.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assemblies\Newtonsoft.Json.dll" CopyToOutputDirectory="PreserveNewest" />
    <None Include="app.config" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="MessagePack.Annotations" Version="3.1.4" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.StringTools" Version="17.11.4" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="MessagePackAnalyzer" Version="3.1.4" PrivateAssets="all" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
  </ItemGroup>

</Project>